name: deploy-to-ec2

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy project to EC2
        uses: ./.github/actions/deploy
        with:
          ec2-ssh-key: ${{ secrets.EC2_SSH_KEY }}
